#!/bin/bash

echo "🔍 Checking Azure App Service connection string configuration..."
echo ""
echo "För att kontrollera connection string i Azure, kör:"
echo ""
echo "az webapp config connection-string list \\"
echo "  --name scheduler-mvp-app \\"
echo "  --resource-group scheduler-mvp-rg"
echo ""
echo "Om connection string saknas eller är fel, sätt den med:"
echo ""
echo "az webapp config connection-string set \\"
echo "  --name scheduler-mvp-app \\"
echo "  --resource-group scheduler-mvp-rg \\"
echo "  --connection-string-type PostgreSQL \\"
echo "  --settings DefaultConnection=\"Host=db.anebyqfrzsuqwrbncwxt.supabase.co;Port=5432;Database=postgres;Username=postgres;Password=bunch-hiccups-misery-extreme;SSL Mode=Require;Trust Server Certificate=true\""
echo ""
echo "Alternativt, om du använder App Settings istället för Connection Strings:"
echo ""
echo "az webapp config appsettings set \\"
echo "  --name scheduler-mvp-app \\"
echo "  --resource-group scheduler-mvp-rg \\"
echo "  --settings ConnectionStrings__DefaultConnection=\"Host=db.anebyqfrzsuqwrbncwxt.supabase.co;Port=5432;Database=postgres;Username=postgres;Password=bunch-hiccups-misery-extreme;SSL Mode=Require;Trust Server Certificate=true\""

